demo/demo/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^todo/', include('todo.urls')),
    url(r'^admin/', admin.site.urls),
]

demo/todo/urls.py
from django.conf.urls import url

from . import views

app_name = 'todo'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^insert/$', views.insert, name='insert'),
    url(r'^check/$', views.check, name='check'),
    url(r'^clear/$', views.clear, name='clear'),
]

demo/todo/models.py
from django.db import models


class TodoItem(models.Model):
    PRIO_CHOICES = (
        (0, 'None'),
        (1, 'Low'),
        (2, 'Medium'),
        (3, 'High'),
    )

    description = models.CharField(max_length=200)
    priority = models.IntegerField(choices=PRIO_CHOICES)
    checked = models.BooleanField(default=False)

    def __str__(self):
        return '[{0}]{1}({2})'.format(self.id, self.description, self.priority)

demo/todo/forms.py
from django import forms

from .models import TodoItem


class TodoForm(forms.Form):
    description = forms.CharField(label='Task', max_length=200)
    priority = forms.ChoiceField(label='Prio', choices=TodoItem.PRIO_CHOICES)

    priority.widget.attrs.update({'class': 'browser-default'})

demo/todo/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .forms import TodoForm
from .models import TodoItem


def index(request):
    todo_items = TodoItem.objects.order_by('-priority')
    context = {
        'unchecked': [i for i in todo_items if not i.checked],
        'checked': [i for i in todo_items if i.checked],
        'form': TodoForm(),
    }
    return render(request, template_name='todo/index.html', context=context)


def insert(request):
    """Insert a new todo item."""
    try:
        description = request.POST['description']
        priority = request.POST['priority']
    except KeyError:
        # Invalid POST data, redirect to index
        return HttpResponseRedirect(reverse('todo:index'))

    todo = TodoItem(description=description, priority=priority)
    todo.save()

    return HttpResponseRedirect(reverse('todo:index'))


def check(request):
    """Mark a task as done or undone.

    The task ID should be sent as a GET parameter.
    """
    try:
        item_id = request.GET['id']
        item = TodoItem.objects.get(id=item_id)
    except (KeyError, TodoItem.DoesNotExist):
        # Invalid POST data, redirect to index
        return HttpResponseRedirect(reverse('todo:index'))

    if item.checked:
        item.checked = False
    else:
        item.checked = True
    item.save()

    return HttpResponseRedirect(reverse('todo:index'))


def clear(request):
    """Delete all Tasks."""
    TodoItem.objects.all().delete()

    return HttpResponseRedirect(reverse('todo:index'))

demo/todo/templates/todo/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>ToDo List ({{ unchecked|length }})</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'todo/style.css' %}" />
    <!-- Materialize CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
    <!-- FontAwesome -->
    <link href="https://opensource.keycdn.com/fontawesome/4.7.0/font-awesome.min.css" rel="stylesheet">
</head>
<body class="grey lighten-3">
    <nav class="grey darken-3">
        <div class="container">
            <div class="nav-wrapper">
                <span class="title">ToDo Tasks ({{ unchecked|length }})</span>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="card-panel">
            <div class="row">
                <form class="col s12" action="{% url 'todo:insert' %}" method="post">
                    {% csrf_token %}

                    <div class="row">
                        <div class="input-field  col s12 m2">
                            {{ form.priority }}
                        </div>
                        <div class="input-field col s12 m8">
                            {{ form.description.label_tag }}
                            {{ form.description }}
                        </div>
                        <div class="input-field col s12 m2">
                            <button class="btn blue" type="submit">add</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="row">
                <div class="col l10 offset-l1 s12">
                {% if unchecked or checked %}
                    <ul>
                    {% for item in unchecked %}
                        <li class="task-item prio{{item.priority}}">
                            <a class="prio{{item.priority}}" href="{% url 'todo:check' %}?id={{item.id}}">
                                <i class="check-button fa fa-square-o"></i>
                                {{ item.description }}
                            </a>
                        </li>
                    {% endfor %}
                    {% for item in checked %}
                    <li class="task-item prio{{item.priority}} checked">
                        <a class="prio{{item.priority}}" href="{% url 'todo:check' %}?id={{item.id}}">
                            <i class="check-button fa fa-check-square-o"></i>
                            {{ item.description }}
                        </a>
                    </li>
                    {% endfor %}
                    </ul>

                {% else %}
                    <p>No items on your list! Start by adding one above...</p>
                {% endif %}
                </div>
            </div>

            <div class="row">
                <div class="col l3 offset-l9 s12">
                    <a class="btn red" href="{% url 'todo:clear' %}"
                       onclick="return confirm('Are you sure?');">Delete All</a>
                </div>
            </div>
        </div>
    </div>
    <!-- jQuery and Materialize CSS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
    <script>
        $(document).ready(function() {
            $('select').material_select();
        });
    </script>
</body>
</html>